site_name: Distributed Government Guide
repo_url: https://github.com/distributedgov/guide
site_url: https://handbook.civicactions.com/en/latest/
site_description: Helping public service teams build highly effective remote and telework environments.
theme:
    name: readthedocs
plugins:
    - search
extra_css:
    - css/extra.css

pages:
    - Welcome: README.md
    - Why: why.md
    - Getting started: getting-started.md
    - Security: security.md
    - Communications: communications.md
    - Meetings: meetings.md
    - Managing: managing.md
    - Project management: project-management.md
    - Technology: technology.md
    - Policies: policies.md
    - Training: training.md
    - Help: help.md
    - License: license-info.md

markdown_extensions:
    - toc:
        permalink: "#"
