site_name: Distributed Government Guide
repo_url: https://github.com/distributedgov/guide
site_url: https://handbook.civicactions.com/en/latest/
theme:
    name: readthedocs
plugins:
    - search
extra_css:
    - css/extra.css

pages:
    - Welcome: README.md
    - Why: why.md
    - Getting started: getting-started.md
    - Security: security.md
    - Communications: communications.md
    - Meetings: meetings.md
    - Technology: technology.md
    - Policies: policies.md
    - Help: help.md
    - License: license-info.md
